name: QuantumCubes
version: 1.0.0
author: Axyss
main: me.axyss.quantumcubes.Main
api-version: 1.13
depend: [ProtocolLib]

commands:
  QuantumCubes:
    description: Gives a player a certain amount of Quantum Cubes
    aliases: qc
    usage: "ยง4Usage: /quantumcubes give <player> [amount]"
    permission: quantumcubes.give

permissions:
  quantumcubes.give:
    default: op
  quantumcubes.use:
    default: op
