name: QuantumCubes
version: 1.1.0
author: Axyss
main: me.axyss.quantumcubes.Main
api-version: 1.21
libraries:
  - "org.xerial:sqlite-jdbc:3.43.0.0"
  - "com.google.code.gson:gson:2.10.1"
depend: [ProtocolLib]

commands:
  quantumcubes:
    description: Gives a player a certain amount of cubes
    aliases: qc

permissions:
  quantumcubes.help:
    default: op
  quantumcubes.give:
    default: op
  quantumcubes.refresh:
    default: op
  quantumcubes.use:
    default: true
